apiVersion: v1
kind: Secret
metadata:
  name: rails-secrets
type: Opaque
data:
  master-key: $(echo -n "your_actual_master_key" | base64)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-api
  template:
    metadata:
      labels:
        app: rails-api
    spec:
      containers:
      - name: rails-api
        image: gcr.io/quantum-transit-448917-e3/rails-app
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: rails-secrets
              key: master-key
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10  