name: Rails CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Auth to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Install GKE Auth Plugin
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build and Push
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/rails-app .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/rails-app

    - name: Set up GKE credentials
      run: |
        gcloud container clusters get-credentials my-gke-cluster --zone europe-west4-b

    - name: Create Secret
      run: |
        # Delete existing secret if it exists
        kubectl delete secret rails-secrets --ignore-not-found
        
        # Create new secret
        kubectl create secret generic rails-secrets \
          --from-literal=master-key=${{ secrets.RAILS_MASTER_KEY }} --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to GKE
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        envsubst < k8s/deployment.yaml | kubectl apply -f -
