name: CI/CD for Rails on GKE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/rails-app .
        echo ${{ secrets.GCP_SERVICE_KEY }} | gcloud auth activate-service-account --key-file=-
        gcloud auth configure-docker

    - name: Push Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/rails-app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials my-gke-cluster --zone europe-west4-b

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
