name: Rails CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Auth to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build and Push
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/rails-app .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/rails-app

    - name: Set up GKE credentials
      run: |
        gcloud container clusters get-credentials my-gke-cluster --zone europe-west4-b

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
