name: Rails CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install Dependencies
      run: |
        bundle install
        yarn install

    - name: Set up Database
      run: |
        sudo apt-get install sqlite3 libsqlite3-dev
        bundle exec rails db:setup

    - name: Run Tests
      run: bundle exec rspec

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Auth to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Build and Push
      run: |
        gcloud auth configure-docker asia-east1-docker.pkg.dev
        docker build -t asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/myapp/rails:latest .
        docker push asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/myapp/rails:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy myapp \
          --image asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/myapp/rails:latest \
          --platform managed \
          --region asia-east1 \
          --allow-unauthenticated